config/routes.rb
Pigskin::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :picks

  root :to => 'home#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  attr_accessible :name

  has_many :divisions
  has_many :teams
end

app/models/division.rb
class Division < ActiveRecord::Base
  attr_accessible :conference_id, :name

  belongs_to :conference
  has_many :teams
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  attr_accessible :points, :team_id, :user_id, :week_id, :schedule_id

  belongs_to :user
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :away_team_id, :home_team_id, :week_id, :start_time

  belongs_to :week
  belongs_to :away_team, :class_name => "Team", :foreign_key => "away_team_id"
  belongs_to :home_team, :class_name => "Team", :foreign_key => "home_team_id"

end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date

  has_many :weeks
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :code, :conference_id, :division_id, :name

  belongs_to :division
  belongs_to :conference
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :user_name

  has_many :picks

end

app/models/week.rb
class Week < ActiveRecord::Base
  attr_accessible :end_date, :nfl_week, :start_date, :season_id

  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  # GET /picks
  # GET /picks.json
  def index
    @picks = Pick.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @picks }
    end
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
    @picks = current_user.picks

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pick }
    end
  end

  # GET /picks/new
  # GET /picks/new.json
  def new
    if params[:id]
      @teams = Week.find(params[:id]).schedules
    else
      @teams = Week.first.schedules.order("start_time").group_by{ |team| team.start_time.strftime("%c")}
    end
      @pick = Pick.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pick }
    end
  end

  # GET /picks/1/edit
  def edit
    @pick = Pick.find(params[:id])
  end

  # POST /picks
  # POST /picks.json
  def create
    #@pick = Pick.new(params[:pick])

    params[:team].each do |team|
      current_user.picks.create(:schedule_id => team[0],:team_id => team[1], :points => params[:points]["#{team[0]}"])
    end

    respond_to do |format|
      #if @pick.save
        #redirect_to new_pick_path
        #format.html { redirect_to @pick, notice: 'Pick was successfully created.' }
        #format.json { render json: @pick, status: :created, location: @pick }
      #else
      #  format.html { render action: "new" }
      #  format.json { render json: @pick.errors, status: :unprocessable_entity }
      #end
    end
  end

  # PUT /picks/1
  # PUT /picks/1.json
  def update
    @pick = Pick.find(params[:id])

    respond_to do |format|
      if @pick.update_attributes(params[:pick])
        format.html { redirect_to @pick, notice: 'Pick was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick = Pick.find(params[:id])
    @pick.destroy

    respond_to do |format|
      format.html { redirect_to picks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_team(id)
    Team.find(id).name
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/home/index.html.haml
.hero-unit
  %h1 Welcome to the 2012-2013 Pigskin Pool!
  %p
  %p <a class="btn btn-primary btn-large">Learn more »</a>

.row
  .span12
    %p The Pigskin Pool is back for it's 12th season! Make your picks each week and compete for the weekly prize. We have the playoffs too!
    %p Remember, for each person you get to sign up and purchase credits, you will receive a $5 refund on your sign up fee.
    %p See you on the field!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pigskin Pool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">body {padding-top: 60px;padding-bottom: 40px;}</style>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Project name</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><a href="#">Rules</a></li>
            <li><%= link_to 'Picks', picks_path %></li>
            <li><a href="#">Credits</a></li>
            <li><a href="#">Standings</a></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit registration', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%=link_to 'Logout', destroy_user_session_path, :method => :delete%></li>
              </ul>
              </li>
            </ul>
            <% else %>
              <li><%=link_to 'Sign In', new_user_session_path %>  </li>
            <% end %>
          </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div>
<div class="container">
<%= yield %>
<hr>

<footer>
<p>© Pigskin Pick 2012</p>
</footer>

    </div>

</body>
</html>

app/views/picks/_form.html.haml
= form_for @pick do |f|
  - if @pick.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pick.errors.count, "error")} prohibited this pick from being saved:"
      %ul
        - @pick.errors.full_messages.each do |msg|
          %li= msg

  %table.table.table-bordered
    %thead
      %tr
        %th Time
        %th Away
        %th Home
        %th Points
    %tbody
    - @teams.each do |gametime, games|
      %tr
        %td{:colspan => 4}
          %h4
            =gametime
      - games.each do |team|
        %tr
          %td
            = team.start_time.strftime("%H:%M")
          %td
            .contol-group
              .controls
                %input{:id => "team_id_#{team.id}", :name => "team[#{team.id}]", :type => "radio", :value => team.away_team_id}
                = image_tag "#{show_team(team.away_team_id).downcase}.png"
                = show_team(team.away_team_id)
          %td
            .control-group
              .controls
                %input{:id => "team_id_#{team.id}", :name => "team[#{team.id}]", :type => "radio", :value => team.home_team_id}
                = image_tag "#{show_team(team.home_team_id).downcase}.png"
                = show_team(team.home_team_id)
          %td
            .control-group
              .controls
                %input.input-mini{:id => "points_id_#{team.id}", :name => "points[#{team.id}]", :type=> "text"}
  .actions
    = f.submit 'Create Picks', :class => "btn btn-primary"

app/views/picks/edit.html.haml
%h1 Editing pick

= render 'form'

= link_to 'Show', @pick
\|
= link_to 'Back', picks_path

app/views/picks/index.html.haml
%h1 Listing picks

%table
  %tr
    %th User
    %th Week
    %th Team
    %th Points
    %th
    %th
    %th

  - @picks.each do |pick|
    %tr
      %td= pick.user_id
      %td= pick.week_id
      %td= pick.team_id
      %td= pick.points
      %td= link_to 'Show', pick
      %td= link_to 'Edit', edit_pick_path(pick)
      %td= link_to 'Destroy', pick, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Pick', new_pick_path

app/views/picks/new.html.haml
%h1 Picks for week of

.row
  .span12
    = render 'form'

= link_to 'Back', picks_path

app/views/picks/show.html.haml
%p#notice= notice
.row
  .span5
    %table.table.table-bordered
      %thead
        %tr
          %th Team
          %th Points
      %tbody
      - @picks.each do |team|
        %tr
          %td
            = image_tag "#{show_team(team.team_id).downcase}.png"
            = show_team(team.team_id)
          %td
            = team.points

\|
= link_to 'Back', picks_path